apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  message: {{ .Values.message | default "No message was supplied from values.yaml, defaulting to default value set in template: hi :)" | quote }}
